version = 1

[[annotations]]
path = ["vizzyix/images/**.png", "vizzyix/images/**.xcf", "pbtesting/eix.pb"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2025 Bill Binder <dxtwjb@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["REUSE.toml", "AUTHORS", "ChangeLog", ".clang-format"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2025 Bill Binder <dxtwjb@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["scripts/vizzyix.ebuild"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2025 Gentoo Authors"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = ["scripts/eix.ebuild"]
precedence = "aggregate"
SPDX-FileCopyrightText = "1999-2025 Gentoo Authors"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = ["vizzyix/resources.qrc", "pbtesting/eix_pb2.py"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2025 Bill Binder <dxtwjb@gmail.com>"
SPDX-License-Identifier = "GPL-2.0-only"
