version = 1

[[annotations]]
path = ["vizzyix/images/**.png", "vizzyix/images/**.xcf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Bill Binder <dxtwjb@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Bill Binder <dxtwjb@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
