#!/bin/bash
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

# ------------------------------------------------------
# Generate the installable package and ebuild
#
# - generates a new ebuild file if necessary
# - generates the archive
#
# 1. Check version correct in top level meson.build
# 2. Check all changes have been committed
# 3. $ cd scripts
# 4. $ ./mkpackage
# 5. Results in scripts/files
# ------------------------------------------------------

APPNAME=vizzyix
BUILD_DIR=../../meson-build

# Check for uncommitted changes and stop if any are found

HG_STATUS=$(hg status)
if [ -n "$HG_STATUS" ]; then
    echo "STOPPED - please deal with uncommitted changes:"
    echo $HG_STATUS
    exit 1
fi

# Extract version number from top-level meson.build file into APPVER

APPVER=$(awk '{ if ($1 == "version" && $2 == ":") print $3 }' "../meson.build"  | sed 's/'\''//g; s/,//g')
echo "INFO - building package $APPNAME-$APPVER"

# Rebuild clean (and remove the previous dist files)
# Clean only works properly if the dist dir is empty, and the compile
# only updates the version properly if it is clean. Annoying.

rm -rf $BUILD_DIR/meson-dist

if ! meson compile --clean -C $BUILD_DIR ; then
    echo "ERROR - 'meson compile' failed"
    exit 1
fi

# Generate the archive - meson fully tests the result.

if ! meson dist -C $BUILD_DIR ; then
    echo "ERROR - 'meson dist' failed"
    exit 1
fi
echo "INFO - generated archive successfully"

# Looks good, so tag the repository and generate the package files

if ! hg tag "$APPVER"; then
    echo ERROR - failed to tag repository with version
    exit 1
fi

echo "INFO - repository tagged with '$APPVER'"

# Generate files for local overlay

cp vizzyix.ebuild files/${APPNAME}-${APPVER}.ebuild
cp ${BUILD_DIR}/meson-dist/${APPNAME}-${APPVER}.tar.xz files

echo "INFO - saved new ebuild and s/w archive versions in ./scripts/files"

ls -l files

echo "OK!"
